### ISSUE TITLE
make error: hexagon-clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)

### ISSUE THREAD

**Issue by chenjiaoAngel** [XiaoMi/nnlib#3]
![image](https://user-images.githubusercontent.com/38650344/53171717-7ddc0200-361e-11e9-9f2c-70cdf2347477.png)
ubuntu:
Linux version 4.15.0-43-generic (buildd@lcy01-amd64-007)
 (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) 
SDK:
Qualcomm-Hexagon_SDK-3.3.3

first: source setup_sdk_env.source
then: python install_dependencies.py
then: git clone nnlib
then: make tree VERBOSE=1 V=hexagon_Release_dynamic_toolv81_v60
build error:
fatal error: error in backend: Cannot select: t29: v32i32 = select_cc t4, Constant:i32<0>, t9, t11, setne:ch
  t4: i32 = AssertSext t2, ValueType:ch:i8
    t2: i32,ch = CopyFromReg t0, Register:i32 %vreg6
      t1: i32 = Register %vreg6
  t5: i32 = Constant<0>
  t9: v32i32,ch = CopyFromReg t0, Register:v32i32 %vreg64
    t8: v32i32 = Register %vreg64
  t11: v32i32,ch = CopyFromReg t0, Register:v32i32 %vreg63
    t10: v32i32 = Register %vreg63
In function: core_add_d32_mixed_hvx
can you help me to solve this problem

**Comment by lee-bin** [comment]
This reposity is deprecated for latest MACE.
If you only want to use nnlib with MACE, you can just use pre-built library below.
https://github.com/XiaoMi/mace/tree/master/third_party/nnlib/v60

**Comment by chenjiaoAngel** [comment]
If I want to contribute some Code in nnlib.  So, how can I make this code

**Comment by lee-bin** [comment]
Can you build the original code from https://source.codeaurora.org/quic/hexagon_nn/nnlib?

**Comment by chenjiaoAngel** [comment]
No, the building code is from 
https://source.codeaurora.org/quic/hexagon_nn/nnlib?

**Comment by w-adamski** [comment]
@lee-bin could you include (preferably with MACE sources) exact build instructions that will produce a nnlib library that is compatible with MACE? That would include:
- nnlib version (the last commit is from 2019-02-11, and precompiled binaries were added to MACE before that, so most likely those binaries are using older, possibly slower, sources)
- Hexagon SDK version (not every version of Hexagon SDK can build every version of nnlib)
- build command (for example there are differences between toolv72_v60 and toolv82_v60)
- how to build libhexagon_controller.so - is it the same libhexagon_controller.so that is in tensorflow sources: tensorflow/contrib/hvx/hexagon_controller? If it is, which version is used and are there any changes in tensorflow build (for example when building tensorflow I replaced libadsprpc with libcdsprpc in android.min)?

**Comment by lee-bin** [comment]
I will try to build MACE with the latest https://source.codeaurora.org/quic/hexagon_nn/nnlib and update this repo and README with more instructions later, so you can build it.

**Comment by lee-bin** [comment]
@chenjiaoAngel @w-adamski 
Hi all,
This repo has been updated to the 02_06_00 version as in https://source.codeaurora.org/quic/hexagon_nn/nnlib/
You can follow the instructions in [README.HOW_TO_BUILD](https://github.com/XiaoMi/nnlib/blob/master/README.HOW_TO_BUILD) to use the library for MACE.
